name: nepali_english_dual_calendar
description: A customizable Flutter calendar and picker supporting both Bikram Sambat (BS) and Gregorian (AD) systems.
version: 0.0.2
homepage: https://biweshstha.com.np
repository: https://github.com/ShrBwes/nepali_english_calendar

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nepali_utils: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
